### ISSUE TITLE
missing-input-response, missing-input-secret

### ISSUE THREAD

**Issue by arturojain** [confuser/node-recaptcha-middleware#1]

**Comment by confuser** [comment]
Sorry, I don't quite follow what the issue is?

**Comment by exaskye** [comment]
Had the same problem, and messing with the code and using the API directly in curl, it looks like:
- The Recaptcha API uses x-www-form-urlencoded data, not json
- The response body from Request was a string and not a parsed json object

Changing "json: data" to "form: data" and calling JSON.parse on res.body makes the library work for me.

**Comment by confuser** [comment]
This was working when I originally wrote this. How odd. I've made the changes as described by @unascribed and released this as v1.0.1

**Comment by arturojain** [comment]
Great, I was working on finding a fix.
